#include<iostream.h>
#include<process.h>
#include<conio.h>
int main()
{
clrscr();
int a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z;
int aa,ab,ac,ad,ae,af,ag,ah,ai,aj,ak,al,am,an,ao,ap,aq,ar,as,at,au,av,aw,ax,ay,az,azz,azzz;
int a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18;

a=b=c=d=e=f=g=h=i=j=k=l=m=n=o=p=q=r=s=t=u=v=w=x=y=z=aa=ab=ac=ad=ae=af=ag=ah=ai=aj=ak=al=am=an=ao=ap=aq=ar=as=at=au=au=av=aw=ax=ay=az=azz=azzz=a1=a2=a3=a4=a5=a6=a7=a8=a9=a10=a11=a12=a13=a14=a15=a16=a17=a18=72;

cout<<a;
return 0;
}